source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'bootstrap-sass', '2.3.2.0'
#gem 'sprockets', '2.11.0'
gem 'bcrypt-ruby', '3.1.2'
#gem 'faker', '1.1.2'
gem 'faker', '1.4.2'
gem 'will_paginate', '3.0.4'
gem 'bootstrap-will_paginate', '0.0.9'

group :development, :test do
  gem 'web-console', '2.0.0.beta3'
  gem 'sqlite3', '1.3.9'
  gem 'rspec-rails', '~> 2.14.0'
  gem 'factory_girl_rails', '~> 4.2.1'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  #gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'sass-rails', '~> 5.0'
#gem 'uglifier', '>= 1.3.0'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '3.0.4'
#gem 'turbolinks', '1.1.1'
gem 'turbolinks', '~> 2.3.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :test do
	gem 'selenium-webdriver'
	gem 'capybara'
  gem 'cucumber-rails', '1.4.0', :require => false
  gem 'database_cleaner', github: 'bmabey/database_cleaner'
end

group :production do
  gem 'pg', '0.15.1'
  gem 'rails_12factor', '0.0.2'
end
