source 'https://rubygems.org'

gem 'rails', '4.2.2'
group :development do
  gem 'sqlite3', '1.3.9'
end

gem 'sass-rails', '~> 5.0'
#gem 'uglifier', '>= 1.3.0'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails', '3.0.4'
gem 'turbolinks', '1.1.1'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'rspec-rails', '~> 2.14.0'
  gem 'factory_girl_rails', '~> 4.2.1'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

